# Generated by Django 5.0.3 on 2024-03-22 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageNum', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=128)),
                ('pageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.page')),
            ],
        ),
    ]
